provider:
  name: faas
  gateway: http://localhost:8080

functions:
  github-stats:
    lang: node
    handler: ./github-stats
    image: kenfdev/github-stats:0.9.0
    environment:
      write_debug: true
      read_timeout: 30
      write_timeout: 30
      exec_timeout: 30
      API_KEY_NAME: kenfdev
    secrets:
      - github-api-keys
  github-stats-page:
    lang: node
    handler: ./github-stats-page
    image: kenfdev/github-stats-page:0.9.0
    environment:
      content_type: text/html
