provider:
  name: faas
  gateway: http://localhost:8080

functions:
  github-stats:
    lang: node
    handler: ./github-stats
    image: kenfdev/github-stats
    environment:
      read_timeout: 30
    environment_file:
      - env.yml
